language: cpp

branches:
  only:
    - secure_travis

sudo: enabled

before_install:
  - sudo apt-get update
  - sudo apt-get install -y doxygen doxygen-doc doxygen-gui graphviz

script:
  - make doxygen

after_success:
  # Generate the docs only if we can use secure variables
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]] ; then
    chmod 700 .ci/generate_documentation.sh;
    .ci/generate_documentation.sh || travis_terminate 1;
  fi

