# Author: Andreas Rupp, Heidelberg University, 2021.

name: Clang

on: [push]

jobs:
  formatting-check:
    name: Test clang-format to change nothing
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Conduct Clang-Format Test
      uses: HyperHDG/actions@clang-format
