name: CMake

on: [push]

env:
  PYTHON: python3-dev python3-numpy python3-scipy cython3

jobs:
  build_gnu10:
    name: Test build with g++-10
    runs-on: ubuntu-latest
    
    - name: Install Python
      run: sudo apt-get update; sudo apt-get install -y $PYTHON

    - uses: actions/checkout@v2
    - name: Run CMake test
      uses: jidicula/clang-format-action@main
