# Author: Andreas Rupp, Heidelberg University, 2021.

name: CMake

on: [push]

env:
  PYTHON: python3-dev python3-numpy python3-scipy cython3

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        cxx: [g++-10, clang++-10]

    env:
      CXX: ${{ matrix.cxx }}
      OS: ${{ matrix.os }}

    name: Test build with g++-10
    runs-on: ${{env.OS}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive
    - name: Install Python
      run: sudo apt-get update; sudo apt-get install -y ${{env.PYTHON}}
    - name: Conduct CMake Test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{env.CXX}}
