# Author: Andreas Rupp, Heidelberg University, 2021.

name: CMake

on: [push]

env:
  PYTHON: python3-dev python3-numpy python3-scipy cython3


jobs:
  # =============== Test code on Ubuntu 20.04 with all currently available compilers ===============
  build_and_test_ubuntu_20-04:
    strategy:
      matrix:
        os:  [ ubuntu-20.04 ]
        cxx: [ clang++-10, clang++-11, clang++-12, g++-10, g++-11 ]

    env:
      omp_lib: libomp-10-dev libomp-11-dev libomp-12-dev

    name: Test code with ${{ matrix.cxx }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive
    - name: Install Python and CXX compiler
      run: |
        sudo apt-get update;
        sudo apt-get install -y ${{ env.PYTHON }} ${{ matrix.cxx }} ${ env.omp_lib }
    - name: Conduct cmake test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{ matrix.cxx }}
  # =============== Test code on Ubuntu 22.04 with all currently available compilers ===============
  build_and_test_ubuntu_22-04:
    strategy:
      matrix:
        os:  [ ubuntu-22.04 ]
        cxx: [ clang++-11, clang++-12, clang++-13, clang++-14, g++-10, g++-11, g++-12 ]

    env:
      omp_lib: libomp-11-dev libomp-12-dev libomp-13-dev libomp-14-dev

    name: Test code with ${{ matrix.cxx }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive
    - name: Install Python and CXX compiler
      run: |
        sudo apt-get update;
        sudo apt-get install -y ${{ env.PYTHON }} ${{ matrix.cxx }}
    - name: Conduct cmake test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{ matrix.cxx }}
