name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  PYTHON: python3-dev python3-numpy python3-scipy cython3

jobs:
  build_gnu10:
    name: Test build with g++-10
    # The CMake configure and build commands are platform agnostic and should work equally well on
    # Windows or Mac.  You can convert this to a matrix build if you need# cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/
    #      managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    env:
      BUILD_DIRECTORY: build_gnu
      CXX: g++-10

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive

    - name: Install Compiler
      run: sudo apt-get update; sudo apt-get install -y $CXX $PYTHON

    - name: Conduct CMake test
      run: cmake -E make_directory ${{runner.workspace}}/env.BUILD_DIRECTORY
