# Author: Andreas Rupp, Heidelberg University, 2021.

name: CMake

on: [push]

env:
  PYTHON: python3-dev python3-numpy python3-scipy cython3


jobs:
  # =============== Test code on Ubuntu 20.04 with all currently available compilers ===============
  build_and_test_ubuntu_20-04:
    strategy:
      matrix:
        osys: [ ubuntu-20.04 ]
        comp: |
          [ {cxx: clang++-10, lib: libomp-10-dev}, {cxx: clang++-11, lib: libomp-11-dev},
            {cxx: clang++-12, lib: libomp-12-dev}, {cxx: g++-10, comp: }, {cxx: g++-11, comp: } ]

    name: Test code with ${{ matrix.comp.cxx }} on ${{ matrix.osys }}
    runs-on: ${{ matrix.osys }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive
    - name: Install Python and CXX compiler
      run: |
        sudo apt-get update;
        sudo apt-get install -y ${{ env.PYTHON }} ${{ matrix.comp.cxx }} ${{ matrix.comp.lib }}
    - name: Conduct cmake test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{ matrix.cxx }}
  # =============== Test code on Ubuntu 22.04 with all currently available compilers ===============
  build_and_test_ubuntu_22-04:
    strategy:
      matrix:
        os:  [ ubuntu-22.04 ]
        cxx: [ clang++-11, clang++-12, clang++-13, clang++-14, g++-10, g++-11, g++-12 ]

    env:
      omp_lib: libomp5-14

    name: Test code with ${{ matrix.cxx }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive
    - name: Install Python and CXX compiler
      run: |
        sudo apt-get update;
        sudo apt-get install -y ${{ env.PYTHON }} ${{ matrix.cxx }} ${{ env.omp_lib }}
    - name: Conduct cmake test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{ matrix.cxx }}
