# Author: Andreas Rupp, Heidelberg University, 2021.

name: CMake

on: [push]

env:
  PYTHON: python3-dev python3-numpy python3-scipy cython3


jobs:
  # =============== Test code on Ubuntu 20.04 with all currently available compilers ===============
  build_and_test_ubuntu_20-04:
    strategy:
      matrix:
        osys: [ ubuntu-20.04 ]
        comp: [ {cxx: clang++-10, lib: libomp-10-dev}, {cxx: clang++-11, lib: libomp-11-dev},
                {cxx: clang++-12, lib: libomp-12-dev}, {cxx: g++-10}, {cxx: g++-11} ]

    name: Test code with ${{ matrix.comp.cxx }} on ${{ matrix.osys }}
    runs-on: ${{ matrix.osys }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive
    - name: Install Python and CXX compiler
      run: |
        sudo apt-get update;
        sudo apt-get install -y ${{ env.PYTHON }} ${{ matrix.comp.cxx }} ${{ matrix.comp.lib }}
    - name: Conduct cmake test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{ matrix.comp.cxx }}
  # =============== Test code on Ubuntu 22.04 with all currently available compilers ===============
  build_and_test_ubuntu_22-04:
    strategy:
      matrix:
        osys: [ ubuntu-22.04 ]
        comp: [ {cxx: clang++-11, lib: libomp-11-dev}, {cxx: clang++-12, lib: libomp-12-dev},
                {cxx: clang++-13, lib: libomp-13-dev}, {cxx: clang++-14, lib: libomp-14-dev},
                {cxx: g++-10}, {cxx: g++-11}, {cxx: g++-12} ]

    name: Test code with ${{ matrix.comp.cxx }} on ${{ matrix.osys }}
    runs-on: ${{ matrix.osys }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive
    - name: Install Python and CXX compiler
      run: |
        sudo apt-get update;
        sudo apt-get install -y ${{ env.PYTHON }} ${{ matrix.comp.cxx }} ${{ matrix.comp.lib }}
    - name: Conduct cmake test
      uses: HyperHDG/actions@cmake
      with:
        cxx_compiler: ${{ matrix.comp.cxx }}
