name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  PYTHON: python3-dev python3-numpy python3-scipy cython3

jobs:
  build_gnu10:
    name: Test build with g++-10
    runs-on: ubuntu-latest
    env:
      BUILD_DIRECTORY: build_gnu
      CXX: g++-10

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       submodules: recursive

    - name: Install Compiler
      run: sudo apt-get update; sudo apt-get install -y $CXX $PYTHON

    - name: Conduct CMake test
      uses: HyperHDG/actions@cmake
