name: Deploy Wiki

on:
  push:
    branches:
    - gh-wiki

jobs:
  deploy_wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2
    - name: Run deploy_wiki script
      uses: HyperHDG/actions@wiki
      with:
        ci_repo_token: ${{ secrets.CI_REPO_TOKEN }}
        ci_user_name: HyperHDG-CI
        ci_user_mail: HyperHDG@rupp.ink
        wiki_repo_organization: AndreasRupp
        wiki_repo_name: HyperHDG.wiki
